version: "3.9"

services:
  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres

  web:
    image: registry.digitalocean.com/imagez/accountabilibuddies-web:latest
    build: ./web
    ports:
      - 3000:3000
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/buds
      - TEST_DATABASE_URL=postgresql://postgres:postgres@postgres:5432/test